### ISSUE TITLE
Problem with anonymous classes in Component Deployer

### ISSUE THREAD

**Issue by vitkud** [scm4j/scm4j-deployer-engine#1]
When using an anonymous class in Component Deployer, there is an error similar to the following:
> java.lang.NoClassDefFoundError: com/untill/product/agent/Exec$1
> 	at com.untill.product.agent.Exec.realInheritIO(Exec.java:100)
> 	at com.untill.product.agent.Exec.executeCommand(Exec.java:88)
> 	at com.untill.product.agent.Exec.deploy(Exec.java:121)
> 	at org.scm4j.deployer.engine.Deployer.applyCommand(Deployer.java:266)
> 	at org.scm4j.deployer.engine.Deployer.deployComponents(Deployer.java:222)
> 	at org.scm4j.deployer.engine.Deployer.compareAndDeployProducts(Deployer.java:196)
> 	at org.scm4j.deployer.engine.Deployer.deploy(Deployer.java:148)
> 	at org.scm4j.deployer.engine.DeployerEngine.deploy(DeployerEngine.java:30)
> 	at org.scm4j.installer.Installer.lambda$deploy$1(Installer.java:184)
> 	at org.scm4j.installer.Progress$ProcessThread.run(Progress.java:141)
> Caused by: java.lang.ClassNotFoundException: com.untill.product.agent.Exec$1
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	... 10 more

Workaround: use Lambda

**Comment by Kindratte** [comment]
Could't use anon classes in deployers, it's part of design)

вт, 3 апр. 2018 г., 16:04 Vitaliy <notifications@github.com>:
